### PR TITLE
[upstream] Initial framework for background item eviction/promotion

### PR DESCRIPTION
**Pull request by igchor**
Implement stubs for periodic workers for item eviction/promotion. Actual implementation of eviction and promotion will be provided in the next patch.

The idea behing introducing those workers is the following:
- BG eviction: to keep certain amount of free memory and decreasing allocate latency
- BG promotion: to move hot items to memory decresing latency

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/cachelib/43)

### CODE REVIEW

**Comment by igchor** [comment]
If and when this PR is merged into upstream we can followup with PRs that:
- implement params (watermarks, etc.) for BG workers and config support
- implement calculateBatchSize()
- implement eviction for single tier (to NVMe) + optionally promotion from NVMe to DRAM

**Comment by guptask** [comment]
*[`cachelib/allocator/CacheAllocator.h` line 1063 at r1](https://reviewable.io/reviews/intel/cachelib/43#-NJkg5z92S_xDlf05sGM:-NJkg5z92S_xDlf05sGN:b4b595e) ([raw file](https://github.com/intel/cachelib/blob/0fe363ad88682ea345faf497145e09379a9159a3/cachelib/allocator/CacheAllocator.h#L1063)):*
> ```objc
>                       util::Throttler::Config reaperThrottleConfig);
> 
>   bool startNewBackgroundPromoter(
> ```

Is it better to set default values for interval and strategy ? I understand doing so will require a background thread attributes class since multiple default values won't be possible.
e.g. bool startNewBackgroundEvictor(BackgroundThreadOpts opts);

**Comment by guptask** [comment]
*[`cachelib/allocator/CacheAllocatorConfig.h` line 480 at r1](https://reviewable.io/reviews/intel/cachelib/43#-NJkhyhh5w2AoQB4T9II:-NJkhyhh5w2AoQB4T9IJ:bsjlbx0) ([raw file](https://github.com/intel/cachelib/blob/0fe363ad88682ea345faf497145e09379a9159a3/cachelib/allocator/CacheAllocatorConfig.h#L480)):*
> ```objc
>   std::shared_ptr<BackgroundMoverStrategy> backgroundPromoterStrategy;
>   // time interval to sleep between runs of the background evictor
>   std::chrono::milliseconds backgroundEvictorInterval{
> ```

I see now that default values are set in config. So maybe you can ignore my previous comment about background evictor/promoter thread creation api carrying default values for interval and strategy.

**Comment by guptask** [comment]
*[`cachelib/allocator/CacheStats.h` line 293 at r1](https://reviewable.io/reviews/intel/cachelib/43#-NJkiT1qC5-eJsC7GR74:-NJkiT1qC5-eJsC7GR75:b8cd4vu) ([raw file](https://github.com/intel/cachelib/blob/0fe363ad88682ea345faf497145e09379a9159a3/cachelib/allocator/CacheStats.h#L293)):*
> ```objc
> 
> // Mover Stats
> struct BackgroundMoverStats {
> ```

Should this class be renamed to BackgroundMoverLocalStats ? I think adding the term "local" adds clarity to the per-thread stats collection mode.

**Review by guptask — APPROVED** [review]
Overall the PR looks good. Please review the few cosmetic comments.
:lgtm:

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/43#-:-NJkj1En5p0G9vqmFCxI:b-w8yz18)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/43)* status: all files reviewed, 3 unresolved discussions (waiting on @guptask)

___
*[`cachelib/allocator/CacheAllocator.h` line 1063 at r1](https://reviewable.io/reviews/intel/cachelib/43#-NJkg5z92S_xDlf05sGM:-NJkkqYDC447EuaMTXq6:b-t096j9) ([raw file](https://github.com/intel/cachelib/blob/0fe363ad88682ea345faf497145e09379a9159a3/cachelib/allocator/CacheAllocator.h#L1063)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

Is it better to set default values for interval and strategy ? I understand doing so will require a background thread attributes class since multiple default values won't be possible.
e.g. bool startNewBackgroundEvictor(BackgroundThreadOpts opts);
</blockquote></details>

We don't have too many params, so I think it's fine as it is for now. `startNewPoolOptimizer` and others also don't have default params. 
___
*[`cachelib/allocator/CacheAllocatorConfig.h` line 480 at r1](https://reviewable.io/reviews/intel/cachelib/43#-NJkhyhh5w2AoQB4T9II:-NJkm-w19Ol0Mgc1AmeK:b-qlzmqx) ([raw file](https://github.com/intel/cachelib/blob/0fe363ad88682ea345faf497145e09379a9159a3/cachelib/allocator/CacheAllocatorConfig.h#L480)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

I see now that default values are set in config. So maybe you can ignore my previous comment about background evictor/promoter thread creation api carrying default values for interval and strategy.
</blockquote></details>

Yeah, I think it's probably better to have the default values here and perhaps in `enableBackgroundEvictor` function as well eventually.
___
*[`cachelib/allocator/CacheStats.h` line 293 at r1](https://reviewable.io/reviews/intel/cachelib/43#-NJkiT1qC5-eJsC7GR74:-NJkn60N8JXl1cX_hUr2:b-joym89) ([raw file](https://github.com/intel/cachelib/blob/0fe363ad88682ea345faf497145e09379a9159a3/cachelib/allocator/CacheStats.h#L293)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

Should this class be renamed to BackgroundMoverLocalStats ? I think adding the term "local" adds clarity to the per-thread stats collection mode.
</blockquote></details>

Well, we're using this class to aggregate stats from all Bg workers at the end so I'm not sure. This is done inside `getBackgroundMoverStats`

**Pull request closed without merging**
