### PR TITLE
Combined locking with exclusive bit

### PR DESCRIPTION
**Pull request by byrnedj**
For leader and follower - I see about 20% performance improvement in throughput, for follower it is about 10% improvement.

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/cachelib/38)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/38)* status: 0 of 29 files reviewed, 2 unresolved discussions (waiting on @byrnedj)

___
*[`cachelib/allocator/CacheAllocator.h` line 1968 at r3](https://reviewable.io/reviews/intel/cachelib/38#-NHVPDW01e3JZ-khokA0:-NHVPDW01e3JZ-khokA1:b-45ryfb) ([raw file](https://github.com/intel/cachelib/blob/a30f2ac35ea554441093849bcbe18897d322c6b0/cachelib/allocator/CacheAllocator.h#L1968)):*
> ```objc
>   // exposed for the background evictor to iterate through the memory and evict
>   // in batch. This should improve insertion path for tiered memory config
>   size_t traverseAndEvictItems(unsigned int tid, unsigned int pid, unsigned int cid, size_t batch) {
> ```

this (and promotion function) should be adjusted and use similar logic as in findEviction (mark moving first, then exclusive if needed)
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 3260 at r3](https://reviewable.io/reviews/intel/cachelib/38#-NHVQ6jb9gBA1dZLsxNL:-NHVQ6jb9gBA1dZLsxNM:b1oh9zz) ([raw file](https://github.com/intel/cachelib/blob/a30f2ac35ea554441093849bcbe18897d322c6b0/cachelib/allocator/CacheAllocator-inl.h#L3260)):*
> ```objc
>       token = createPutToken(*evicted);
>       if (evicted->markExclusiveWhenMoving()) {
>         unlinkItemExclusive(*evicted);
> ```

I think we need to wakeUp any waiters here as well (similarly to findEviction).
We should probably do this only for mutli-tier case. And for single-tier we might allow readers for moving items (pass false to incRef() call in acquire for single tier)

**Review by byrnedj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/38)* status: 0 of 29 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[`cachelib/allocator/CacheAllocator.h` line 1968 at r3](https://reviewable.io/reviews/intel/cachelib/38#-NHVPDW01e3JZ-khokA0:-NHWF_yh9V79CGqppD-I:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/a30f2ac35ea554441093849bcbe18897d322c6b0/cachelib/allocator/CacheAllocator.h#L1968)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

this (and promotion function) should be adjusted and use similar logic as in findEviction (mark moving first, then exclusive if needed)
</blockquote></details>

Done.
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 3260 at r3](https://reviewable.io/reviews/intel/cachelib/38#-NHVQ6jb9gBA1dZLsxNL:-NHWFUBv6B0kZ0I3qX6k:bb6un1j) ([raw file](https://github.com/intel/cachelib/blob/a30f2ac35ea554441093849bcbe18897d322c6b0/cachelib/allocator/CacheAllocator-inl.h#L3260)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think we need to wakeUp any waiters here as well (similarly to findEviction).
We should probably do this only for mutli-tier case. And for single-tier we might allow readers for moving items (pass false to incRef() call in acquire for single tier)
</blockquote></details>

Done

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/38)* status: 2 of 29 files reviewed, 2 unresolved discussions (waiting on @byrnedj)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 3260 at r3](https://reviewable.io/reviews/intel/cachelib/38#-NHVQ6jb9gBA1dZLsxNL:-NH_ogCW3SAiyZLSfqe2:bjwvu4q) ([raw file](https://github.com/intel/cachelib/blob/a30f2ac35ea554441093849bcbe18897d322c6b0/cachelib/allocator/CacheAllocator-inl.h#L3260)):*
<details><summary><i>Previously, byrnedj (Daniel Byrne) wrote…</i></summary><blockquote>

Done
</blockquote></details>

How about chained items? Will you `wakeUpWaiters` for them then? Perhpas just add some `TODO` now?
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1040 at r4](https://reviewable.io/reviews/intel/cachelib/38#-NH_nluY9ecKUZkbblOx:-NH_nluY9ecKUZkbblOy:b2p4urj) ([raw file](https://github.com/intel/cachelib/blob/3040d37f39012e8447374fafad6181a34fc68b02/cachelib/allocator/CacheAllocator-inl.h#L1040)):*
> ```objc
>   SCOPE_FAIL { stats_.numRefcountOverflow.inc(); };
> 
>   auto failIfMoving = getNumTiers() > 1 ? true : false;
> ```

nit: you can drop the `? true : false` part ;d
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1362 at r4](https://reviewable.io/reviews/intel/cachelib/38#-NH_o9vk4eVLIpIrSGJZ:-NH_o9vk4eVLIpIrSGJ_:bfqd3k2) ([raw file](https://github.com/intel/cachelib/blob/3040d37f39012e8447374fafad6181a34fc68b02/cachelib/allocator/CacheAllocator-inl.h#L1362)):*
> ```objc
>   // Adding the item to mmContainer has to succeed since no one can remove the item
>   auto& newContainer = getMMContainer(*newItemHdl);
>   auto mmContainerAdded = newContainer.add(*newItemHdl);
> ```

Hm, I think this should still be `replace` after all. Then, you don't nee to call removeFromMMContainer in `traverseAndPromoteItems`

**Review by byrnedj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/38)* status: 1 of 29 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 3260 at r3](https://reviewable.io/reviews/intel/cachelib/38#-NHVQ6jb9gBA1dZLsxNL:-NI9jmkF-0_pf9_n1IsO:bs5v42t) ([raw file](https://github.com/intel/cachelib/blob/a30f2ac35ea554441093849bcbe18897d322c6b0/cachelib/allocator/CacheAllocator-inl.h#L3260)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

How about chained items? Will you `wakeUpWaiters` for them then? Perhpas just add some `TODO` now?
</blockquote></details>

Added for now - chained item PR will address any additional logic.
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1040 at r4](https://reviewable.io/reviews/intel/cachelib/38#-NH_nluY9ecKUZkbblOx:-NI9kN8NAX0kYGxTcA5a:bb7f2mf) ([raw file](https://github.com/intel/cachelib/blob/3040d37f39012e8447374fafad6181a34fc68b02/cachelib/allocator/CacheAllocator-inl.h#L1040)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: you can drop the `? true : false` part ;d
</blockquote></details>

done
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1362 at r4](https://reviewable.io/reviews/intel/cachelib/38#-NH_o9vk4eVLIpIrSGJZ:-NI9jw2e2Qhp2XloIrsW:b4woq5w) ([raw file](https://github.com/intel/cachelib/blob/3040d37f39012e8447374fafad6181a34fc68b02/cachelib/allocator/CacheAllocator-inl.h#L1362)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, I think this should still be `replace` after all. Then, you don't nee to call removeFromMMContainer in `traverseAndPromoteItems`
</blockquote></details>

I am not sure because `replaceInMMContainer` will only replace if oldItem exists in mmContainer due to the short circuit evaluation. But here we have already removed the oldItem from mmContainer in most cases (expect for promotion case).

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/38)* status: 1 of 29 files reviewed, 1 unresolved discussion (waiting on @byrnedj)

___
*[`cachelib/allocator/CacheAllocator.h` line 2083 at r6](https://reviewable.io/reviews/intel/cachelib/38#-NI9mXVR-IUBSCK4PLiQ:-NI9mXVR-IUBSCK4PLiR:bmnfcqa) ([raw file](https://github.com/intel/cachelib/blob/f5e5a5d476416afde71f03e0c038e9a2ab592218/cachelib/allocator/CacheAllocator.h#L2083)):*
> ```objc
>       } else {
> 	 //we failed to allocate a new item, this item is no  longer moving
> 	candidate->unmarkMoving();
> ```

I think you need to handle possible `ref==0` case here as well.
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1362 at r4](https://reviewable.io/reviews/intel/cachelib/38#-NH_o9vk4eVLIpIrSGJZ:-NI9lOihDlcdTZA4DVkY:brzaikh) ([raw file](https://github.com/intel/cachelib/blob/3040d37f39012e8447374fafad6181a34fc68b02/cachelib/allocator/CacheAllocator-inl.h#L1362)):*
<details><summary><i>Previously, byrnedj (Daniel Byrne) wrote…</i></summary><blockquote>

I am not sure because `replaceInMMContainer` will only replace if oldItem exists in mmContainer due to the short circuit evaluation. But here we have already removed the oldItem from mmContainer in most cases (expect for promotion case).
</blockquote></details>

Ok, I see, but we still need to make sure the oldItem is removed from the MMContainer. Perhaps some assert in findEviction and BGEvciction then? And I'm not sure if ChainedItem support won't require any changes

**Review by byrnedj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/38)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[`cachelib/allocator/CacheAllocator.h` line 2083 at r6](https://reviewable.io/reviews/intel/cachelib/38#-NI9mXVR-IUBSCK4PLiQ:-NIIzWRi1yqGcm84kHhw:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/f5e5a5d476416afde71f03e0c038e9a2ab592218/cachelib/allocator/CacheAllocator.h#L2083)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think you need to handle possible `ref==0` case here as well.
</blockquote></details>

Done.
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1362 at r4](https://reviewable.io/reviews/intel/cachelib/38#-NH_o9vk4eVLIpIrSGJZ:-NIIzNQL5Zh7w8KHSfu9:bct8i0d) ([raw file](https://github.com/intel/cachelib/blob/3040d37f39012e8447374fafad6181a34fc68b02/cachelib/allocator/CacheAllocator-inl.h#L1362)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Ok, I see, but we still need to make sure the oldItem is removed from the MMContainer. Perhaps some assert in findEviction and BGEvciction then? And I'm not sure if ChainedItem support won't require any changes
</blockquote></details>

remove with the iterator returns void - removedLock in mmContainer does not fail so I think we can assume that it succeeded.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/38#-:-NIJoJSs8tm-oqoBLuOi:bnfp4nl)* status: 0 of 30 files reviewed, all discussions resolved

**Pull request merged**
