### PR TITLE
Fix ReaperSkippingSlabTraversalWhileSlabReleasing test

### PR DESCRIPTION
**Pull request by vinser52**
This change is [Reviewable](https://reviewable.io/reviews/intel/cachelib/19)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
Please add some description to the commit. What was the problem and how does this fix it?

> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/19#-:-NC2QGbd8bwLJmukcXn-:blm87xr)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @byrnedj and @vinser52)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1644 at r1](https://reviewable.io/reviews/intel/cachelib/19#-NC2Q5JX-Q_0NVml1lZV:-NC2Q5JY8q6u8vlv5elj:bwiezxy) ([raw file](https://github.com/intel/cachelib/blob/41f5d13971d818ed083c3f7e3a05f3e3b609e2ba/cachelib/allocator/CacheAllocator-inl.h#L1644)):*
> ```objc
>     TierId tid, PoolId pid, Item& item) {
>   if(item.isChainedItem()) return {}; // TODO: We do not support ChainedItem yet
>   if(item.isExpired()) {
> ```

nit: you could use removeIfExpired (if you can get a handle first or change the predicate).

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/19)* status: all files reviewed, 1 unresolved discussion (waiting on @byrnedj and @vinser52)

**Review by vinser52 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/19#-:-NC62YtE-XQq0wZkILpE:bb6un1j)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1644 at r1](https://reviewable.io/reviews/intel/cachelib/19#-NC2Q5JX-Q_0NVml1lZV:-NC6-EaR7VkTeyIa8gYk:bna5swd) ([raw file](https://github.com/intel/cachelib/blob/41f5d13971d818ed083c3f7e3a05f3e3b609e2ba/cachelib/allocator/CacheAllocator-inl.h#L1644)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: you could use removeIfExpired (if you can get a handle first or change the predicate).
</blockquote></details>

I saw `removeIfExpired()` function. But I do not want to use it because `tryEvictToNextMemoryTier()` function can be called on the hot path.  And `removeIfExpired()` function calls `accessContainer_->removeIf()` with predicate to check if item is expired.  Internally it grabs the bucket lock. I think it is too expensive on the hot path.
Furthermore, to call `removeIfExpired()` function we need to acquire a handle in that particular case. And think it is also might have some overhead because of atomic operation internally. All this action only need if the item is really expired - I believe, more frequently, `item.isExpired()` is `false` on this path.

But I have implemented another refactoring. When I did rebase of develop branch I blamed such refactoring... But now doing it by myself.
Less code we touch - less merge conflicts we have during rebase

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/19#-:-NC6ZBSb3iVu95huKbhV:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @byrnedj, @igchor, and @vinser52)

___
*[`run_tests.sh` line 4 at r3](https://reviewable.io/reviews/intel/cachelib/19#-NC6Z2RJ5D6cUQjMT2n_:-NC6Z2RK76A9mIABs869:b-g6fgmd) ([raw file](https://github.com/intel/cachelib/blob/a4c4ab370780615027361cd9ce0c4840162d99db/run_tests.sh#L4)):*
> ```Shell
> 
> # Newline separated list of tests to ignore
> BLACKLIST="allocator-test-AllocatorTypeTest
> ```

why did you remove that?

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/19)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @byrnedj and @igchor)

___
*[`run_tests.sh` line 4 at r3](https://reviewable.io/reviews/intel/cachelib/19#-NC6Z2RJ5D6cUQjMT2n_:-NCC2vhAEdRor6trl3QW:b-sxphi9) ([raw file](https://github.com/intel/cachelib/blob/a4c4ab370780615027361cd9ce0c4840162d99db/run_tests.sh#L4)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why did you remove that?
</blockquote></details>

I would ask why we have it in the black list. As I remember we created this blacklist to disable tests that are failed even on mainline. But bow this test are passed on mainline.
The issue fixed by this PR was introduced by me when I implemented transparent async Item movement. And if that test was enabled we would catch the issue during initial PR review.

**Comment by byrnedj** [comment]
> :lgtm:
> 
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/intel/cachelib/19#-:-NC6ZBSb3iVu95huKbhV:bnfp4nl)_ status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @byrnedj, @igchor, and @vinser52)
> 
> _[`run_tests.sh` line 4 at r3](https://reviewable.io/reviews/intel/cachelib/19#-NC6Z2RJ5D6cUQjMT2n_:-NC6Z2RK76A9mIABs869:b-g6fgmd) ([raw file](https://github.com/intel/cachelib/blob/a4c4ab370780615027361cd9ce0c4840162d99db/run_tests.sh#L4)):_
> 
> > ```shell
> > # Newline separated list of tests to ignore
> > BLACKLIST="allocator-test-AllocatorTypeTest
> > ```
> 
> why did you remove that?

Because this is the test suite that was failing. 

I agree with the logic behind refactoring removeIf - and it does effect item reaper code path so we may have merge conflicts later with upstream.

I can compile and pass all tests.

**Review by byrnedj — APPROVED** [review]

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/19)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @byrnedj and @igchor)

___
*[`run_tests.sh` line 4 at r3](https://reviewable.io/reviews/intel/cachelib/19#-NC6Z2RJ5D6cUQjMT2n_:-NCKMSCI1hn6DDmgZ7mu:b-57lzz0) ([raw file](https://github.com/intel/cachelib/blob/a4c4ab370780615027361cd9ce0c4840162d99db/run_tests.sh#L4)):*
> Because this is the test suite that was failing.

Yeah, I remember it. My point was that we should remove this from blacklist earlier (when test suite was fixed by Meta)

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/19)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @byrnedj and @igchor)

___
*[`run_tests.sh` line 4 at r3](https://reviewable.io/reviews/intel/cachelib/19#-NC6Z2RJ5D6cUQjMT2n_:-NCKMoAM6w6vhKEya-4W:bl09215) ([raw file](https://github.com/intel/cachelib/blob/a4c4ab370780615027361cd9ce0c4840162d99db/run_tests.sh#L4)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

> Because this is the test suite that was failing.

Yeah, I remember it. My point was that we should remove this from blacklist earlier (when test suite was fixed by Meta)

</blockquote></details>

Which merge conflicts did you mean?

**Pull request merged**
