### PR TITLE
Fix moveRegularItemWithSync and add tests

### PR DESCRIPTION
**Pull request by vinser52**
This change is [Reviewable](https://reviewable.io/reviews/intel/cachelib/27)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/27#-:-NDnQyKq0Mm3-BuuUeKF:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @byrnedj and @vinser52)

___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 128 at r1](https://reviewable.io/reviews/intel/cachelib/27#-NDnQd8T-7mOxcqKZQEj:-NDnQd8T-7mOxcqKZQEk:b-e4pjuw) ([raw file](https://github.com/intel/cachelib/blob/777ffbdbf1bef0425cc4ccb98d01b84c27190b90/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L128)):*
> ```objc
>   }
> 
>   void testMultiTiersRemoveDuringEviction() {
> ```

nit: you could probably make a generic function which would accept std::function `F` as a param and call `F` inside moveCB instead of copy-pasting the initialization phase.
___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 150 at r1](https://reviewable.io/reviews/intel/cachelib/27#-NDnQAatDej6rK6S_YCA:-NDnOhXu85UyVQo2Hqp1:b-687yea) ([raw file](https://github.com/intel/cachelib/blob/777ffbdbf1bef0425cc4ccb98d01b84c27190b90/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L150)):*
> ```objc
>       t = std::make_unique<std::thread>([&](){ alloc->remove(key); });
>       // sleep to make sure async thread calls remove(key)
>       std::this_thread::sleep_for(std::chrono::milliseconds(100));
> ```

nit: instead of this sleep you could probably use latches quite easily to make this deterministic: https://github.com/facebook/folly/blob/main/folly/synchronization/Latch.h
___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 200 at r1](https://reviewable.io/reviews/intel/cachelib/27#-NDnQR4q8ruY4fA2D9FR:-NDnQR4q8ruY4fA2D9FS:b-qmhu3f) ([raw file](https://github.com/intel/cachelib/blob/777ffbdbf1bef0425cc4ccb98d01b84c27190b90/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L200)):*
> ```objc
>             });
>         // sleep to make sure async thread calls remove(key)
>         std::this_thread::sleep_for(std::chrono::milliseconds(100));
> ```

nit: similarly as above + comment is wrong (should be insertOrReplace)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/27)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @byrnedj and @vinser52)

___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 171 at r2](https://reviewable.io/reviews/intel/cachelib/27#-NE1Q-uKER7bUon_s6mr:-NE1Q-uKER7bUon_s6ms:btp15yf) ([raw file](https://github.com/intel/cachelib/blob/9c10d5980ce0357cd744f19f0357a5251f0b3f42/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L171)):*
> ```objc
>       auto key = oldItem.getKey();
>       t = std::make_unique<std::thread>([&](){
>             latch.count_down();
> ```

shouldnt this be after the remove? or are you trying to interleave the execution of remove with memcpy?
if this you just want to execute the remove and wait for completion then you could probably even just call join immediately, right?

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/27)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 171 at r2](https://reviewable.io/reviews/intel/cachelib/27#-NE1Q-uKER7bUon_s6mr:-NE1Rat_3vYokTy8ZIIg:bjlzrwy) ([raw file](https://github.com/intel/cachelib/blob/9c10d5980ce0357cd744f19f0357a5251f0b3f42/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L171)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

shouldnt this be after the remove? or are you trying to interleave the execution of remove with memcpy?
if this you just want to execute the remove and wait for completion then you could probably even just call join immediately, right?
</blockquote></details>

Remove call is blocked (on wait context) till async move is completed. So that we cannot call latch.count_down() after remove because it will cause deadlock.

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/27)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 171 at r2](https://reviewable.io/reviews/intel/cachelib/27#-NE1Q-uKER7bUon_s6mr:-NE1S7S55ruSVGwrQBMw:b220c4t) ([raw file](https://github.com/intel/cachelib/blob/9c10d5980ce0357cd744f19f0357a5251f0b3f42/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L171)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Remove call is blocked (on wait context) till async move is completed. So that we cannot call latch.count_down() after remove because it will cause deadlock.
</blockquote></details>

I understand that ideally latch.count_down() should be called when the thread hanged on the wait context, but it is not possible to implement in the test.

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/27)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 171 at r2](https://reviewable.io/reviews/intel/cachelib/27#-NE1Q-uKER7bUon_s6mr:-NE5YJqRE1AZGsXTlqZJ:bddix2l) ([raw file](https://github.com/intel/cachelib/blob/9c10d5980ce0357cd744f19f0357a5251f0b3f42/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L171)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I understand that ideally latch.count_down() should be called when the thread hanged on the wait context, but it is not possible to implement in the test.
</blockquote></details>

I have added comments as we discussed in the chat

**Pull request merged**
