### PR TITLE
chained items implementation for multi-tier

### PR DESCRIPTION
**Pull request by byrnedj**
Support for chained items in multi-tier environment.

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/cachelib/28)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/28)* status: all files reviewed, 4 unresolved discussions (waiting on @byrnedj and @vinser52)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1522 at r1](https://reviewable.io/reviews/intel/cachelib/28#-NEh3Znc97Ftdi0qkVp6:-NEh3Znc97Ftdi0qkVp7:btxxgy1) ([raw file](https://github.com/intel/cachelib/blob/e222ff0a95154241dcb494253e4b45e728d0918a/cachelib/allocator/CacheAllocator-inl.h#L1522)):*
> ```objc
>         auto *candidate_ = toRecycle_;
>         
>         // if this is last tier then we should get the parent item since
> ```

why get the parent only if this is the last tier? I think we should always evict the entire chain (parent)
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1674 at r1](https://reviewable.io/reviews/intel/cachelib/28#-NEh41xOBeYQhf3sh_jj:-NEh41xP5BnF4KApC3tI:b2jnir6) ([raw file](https://github.com/intel/cachelib/blob/e222ff0a95154241dcb494253e4b45e728d0918a/cachelib/allocator/CacheAllocator-inl.h#L1674)):*
> ```objc
>     if(item.isChainedItem()) {
>         // allocateInternal might trigger another eviction
>         auto parentHandle = findInternal(item.asChainedItem().getParentItem(compressor_).getKey());
> ```

I think you should verify if the handle you found is indeed the parent (someone might have transferred it in the meantime). Similar to: `validateAndGetParentHandleForChainedMoveLocked` function
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1689 at r1](https://reviewable.io/reviews/intel/cachelib/28#-NEh4lVwDbZpNenU84Fa:-NEh4lVwDbZpNenU84Fb:bb1c29o) ([raw file](https://github.com/intel/cachelib/blob/e222ff0a95154241dcb494253e4b45e728d0918a/cachelib/allocator/CacheAllocator-inl.h#L1689)):*
> ```objc
>     if (newItemHdl) {
>       XDCHECK_EQ(newItemHdl->getSize(), item.getSize());
>       if (item.isChainedItem() && moveChainedItem(item.asChainedItem(), newItemHdl)) {
> ```

this will require having moveCb set up, right? I think we should eventually implement chained item movement the same as for regular items - with transparent sync. However, this probably might be the next step - for now, maybe just some TODO comment?
___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 178 at r1](https://reviewable.io/reviews/intel/cachelib/28#-NEh59PbAsOk7nXNZ289:-NEh59PbAsOk7nXNZ28A:b-45hacl) ([raw file](https://github.com/intel/cachelib/blob/e222ff0a95154241dcb494253e4b45e728d0918a/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L178)):*
> ```objc
>     itemHandle.reset();
>     ASSERT_NE(nullptr, alloc->allocate(pid, "hello2", exhaustedSize));
>   }
> ```

Do you check that any items have been moved (and not just evicted)?
___
*[`cachelib/allocator/tests/BaseAllocatorTest.h` line 4861 at r1](https://reviewable.io/reviews/intel/cachelib/28#-NEh5NHz0VqF_mnyd1e6:-NEh5NHz0VqF_mnyd1e7:bx9d7s2) ([raw file](https://github.com/intel/cachelib/blob/e222ff0a95154241dcb494253e4b45e728d0918a/cachelib/allocator/tests/BaseAllocatorTest.h#L4861)):*
> ```objc
>     const auto poolSize = numBytes;
> 
>     const std::set<uint32_t> allocSizes = {170, 270, 570, 1070, 2070, 5070};
> ```

Coul you please make this change in a separate commit and describe why it's needed?

**Review by byrnedj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/28)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @igchor and @vinser52)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1522 at r1](https://reviewable.io/reviews/intel/cachelib/28#-NEh3Znc97Ftdi0qkVp6:-NEr5aWr96E55resB0fw:bx6oemm) ([raw file](https://github.com/intel/cachelib/blob/e222ff0a95154241dcb494253e4b45e728d0918a/cachelib/allocator/CacheAllocator-inl.h#L1522)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why get the parent only if this is the last tier? I think we should always evict the entire chain (parent)
</blockquote></details>

Because if we are not in last tier we can just move the chained item to the next tier. Items in the same chain can reside in different tiers - that way we don't have to move entire chain from tier i to i+1. But if we are evicting out of the last tier - we should remove the entire chain.
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1674 at r1](https://reviewable.io/reviews/intel/cachelib/28#-NEh41xOBeYQhf3sh_jj:-NEr8iBl1x0nK7skgP0k:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/e222ff0a95154241dcb494253e4b45e728d0918a/cachelib/allocator/CacheAllocator-inl.h#L1674)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think you should verify if the handle you found is indeed the parent (someone might have transferred it in the meantime). Similar to: `validateAndGetParentHandleForChainedMoveLocked` function
</blockquote></details>

Done.
___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 178 at r1](https://reviewable.io/reviews/intel/cachelib/28#-NEh59PbAsOk7nXNZ289:-NEuFVtI563OGbQBH5ta:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/e222ff0a95154241dcb494253e4b45e728d0918a/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L178)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Do you check that any items have been moved (and not just evicted)?
</blockquote></details>

Done.
___
*[`cachelib/allocator/tests/BaseAllocatorTest.h` line 4861 at r1](https://reviewable.io/reviews/intel/cachelib/28#-NEh5NHz0VqF_mnyd1e6:-NEuFX4G5eSE3IVWU6Ut:btpicql) ([raw file](https://github.com/intel/cachelib/blob/e222ff0a95154241dcb494253e4b45e728d0918a/cachelib/allocator/tests/BaseAllocatorTest.h#L4861)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Coul you please make this change in a separate commit and describe why it's needed?
</blockquote></details>

Done - see next commit.

**Review by igchor — COMMENTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/28)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @vinser52)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1522 at r1](https://reviewable.io/reviews/intel/cachelib/28#-NEh3Znc97Ftdi0qkVp6:-NEvGdnCCpXTOvZCGueE:b7w5vib) ([raw file](https://github.com/intel/cachelib/blob/e222ff0a95154241dcb494253e4b45e728d0918a/cachelib/allocator/CacheAllocator-inl.h#L1522)):*
<details><summary><i>Previously, byrnedj (Daniel Byrne) wrote…</i></summary><blockquote>

Because if we are not in last tier we can just move the chained item to the next tier. Items in the same chain can reside in different tiers - that way we don't have to move entire chain from tier i to i+1. But if we are evicting out of the last tier - we should remove the entire chain.
</blockquote></details>

got, it, thanks
___
*[`cachelib/allocator/tests/BaseAllocatorTest.h` line 4861 at r1](https://reviewable.io/reviews/intel/cachelib/28#-NEh5NHz0VqF_mnyd1e6:-NEvKC4ZEN_a0_69r6dI:bjragq1) ([raw file](https://github.com/intel/cachelib/blob/e222ff0a95154241dcb494253e4b45e728d0918a/cachelib/allocator/tests/BaseAllocatorTest.h#L4861)):*
<details><summary><i>Previously, byrnedj (Daniel Byrne) wrote…</i></summary><blockquote>

Done - see next commit. 
</blockquote></details>

Thanks, looks good. I'd like to keep the history when merging - could you keep this commit, and squash remaining ones into a single one (so this PR would have 2 PRs in total)?

Also, there is still some merge conflict

**Comment by byrnedj** [comment]
updated to use chainedItemLocks_ as sync once the moving bit for the chained item has been set. 
-acquiring the chained item lock can fail if someone is updating the chain, if acquiring the lock fails then we will fail the eviction.
-we can't wait on the chained item lock because that would cause deadlock if the chained item is a head item in the chain (the handle is required for transferChainLocked and forEachChainedItem, and probably some others). the deadlock occurs if the chained item is marked moving and then waits on the chained item lock. But the chained item lock is held by the thread that is waiting for the moving chained item.

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/28)* status: 0 of 36 files reviewed, 12 unresolved discussions (waiting on @byrnedj and @vinser52)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 546 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJ87hhD3vk3HSh3IqHu:-NJ87hhD3vk3HSh3IqHv:b-vv1k6y) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L546)):*
> ```objc
> template <typename CacheTrait>
> typename CacheAllocator<CacheTrait>::WriteHandle
> CacheAllocator<CacheTrait>::allocateChainedItemInternalTierForMoving(
> ```

what's the difference between `allocateChainedItemInternalTierForMoving` and `allocateChainedItemInternalTier`? can we unify them?
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 809 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJ88DQQ7zdQEtr_YjLt:-NJ88DQQ7zdQEtr_YjLu:brefihs) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L809)):*
> ```objc
>   while (curr) {
>     XDCHECK_EQ(curr == headHandle.get() ? 2u : 1u, curr->getRefCount());
>     XDCHECK(curr->isInMMContainer()); 
> ```

some random space here
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 982 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJ88T5KCElJrsRE0SBI:-NJ88T5KCElJrsRE0SBJ:b-qaoqo9) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L982)):*
> ```objc
>   const auto newRes = newMMContainer.add(*newItemHdl);
>   auto& oldMMContainer = getMMContainer(oldItem);
>   // This cannot fail because a old item should not have have been removed
> ```

How can we guarantee that it hasn't been removed? Is it because we hold the lock? If, so, do we have some check after acquiring the lock to make sure that the item is still in correct state?
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 990 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJ88fmJ3CPLIHVQSOzB:-NJ88fmJ3CPLIHVQSOzC:bb7nksj) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L990)):*
> ```objc
> 
>   //if we are moving the head chained item to next tier
>   //
> ```

unnecessary line
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1034 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJ88miO04JQHwBq8h1i:-NJ88miO04JQHwBq8h1j:b-yw84e9) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L1034)):*
> ```objc
>                                                    bool nascent,
>                                                    const Item* toRecycle) {
>   if ( (!it.isChainedItem() && !it.isDrained()) ) {
> ```

why this change is needed?
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1057 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJ89Dt368w8QlseAZrm:-NJ89Dt368w8QlseAZrn:b-xwq8ib) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L1057)):*
> ```objc
>   // to a parent item and instead drop the chained item handle. In this case,
>   // we free the chained item directly without calling remove callback.
>   if (it.isChainedItem() && toRecycle == nullptr) {
> ```

just to make sure, if `is.isChainedItem() && toRecycle != nullptr` we will return kRecycled later and not call allocator->free() right?
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1608 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJ89_gH9iXNwBB2-Ky_:-NJ89_gH9iXNwBB2-Kya:b-wlnuu4) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L1608)):*
> ```objc
>   auto res = replaceChainedItemLockedForMoving(oldItem, newItemHdl, parent);
>   XDCHECK(res);
>   //auto ref = oldItem.decRef();
> ```

why this is commented out?
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1801 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJ89eImBgxE0ECkRbSE:-NJ89eImBgxE0ECkRbSF:b-7galux) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L1801)):*
> ```objc
>     mmContainer.withEvictionIterator([this, pid, cid, &candidate, &toRecycle,
>                                       &searchTries, &mmContainer, &lastTier,
>                                       &candidateParent, 
> ```

unnecessary space
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1821 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJ89uju0wuppBDFvaIA:-NJ89uju0wuppBDFvaIB:bf2umfd) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L1821)):*
> ```objc
>                 : nullptr;
>         if (lastTier && candidateParent_ != nullptr) {
>             candidate_ = candidateParent_;
> ```

some comment would be nice here
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1824 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJ8AkSf50ScltR0e8oZ:-NJ8AkSf50ScltR0e8o_:bne1oqw) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L1824)):*
> ```objc
>         }
>   
>         if (shouldWriteToNvmCache(*candidate_) && !token.isValid()) {
> ```

Hm, something wen wrong here (it's broken on develop as well): we are checking token before creating it.
There should be `token = createPutToken()` line somewhere here.
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1888 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJ8Bbju3DPKPDweiKyn:-NJ8Bbjv8z_8zl6vvZ41:b-dick1x) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L1888)):*
> ```objc
>           //unmark child as moving
>           XDCHECK(candidate->isMoving());
>           auto ret = candidate->incRef(false);
> ```

why are we increasing the ref here?
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 2037 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJ8BnM73Wwk8xsGjbJg:-NJ8BnM73Wwk8xsGjbJh:b-575kw1) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L2037)):*
> ```objc
>               item.asChainedItem().getParentItem(compressor_);
>           if (parentItem == &expectedParent) {
>             //search
> ```

do we actually need to search? it seems this is just for validation so perhaps just put it into a separate function and call it only inside XDCHECK()? or

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/28)* status: 0 of 36 files reviewed, 15 unresolved discussions (waiting on @byrnedj and @vinser52)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1831 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJBn1BDDZX3YbzGT3Dr:-NJBn1BDDZX3YbzGT3Ds:batb4y) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L1831)):*
> ```objc
>         //if we are not the last tier
>         //  - attempt to mark the candidate as moving
>         } else if ( !candidate_->isChainedItem() &&
> ```

it'd suggest to extract those more complex conditionals to some separate function (with a descriptive name). It would be easier to undestand
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1890 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJBnHco9mX2FnAUMZ9E:-NJBnHco9mX2FnAUMZ9F:b-qjc6w2) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/CacheAllocator-inl.h#L1890)):*
> ```objc
>           auto ret = candidate->incRef(false);
>           XDCHECK(ret == RefcountWithFlags::incResult::incOk);
>           auto ref = candidate->unmarkMoving();
> ```

perhaps we could create a helper function for unmarking AND calling wakeUpWaiters and use it everywhere? 
___
*[`cachelib/allocator/Refcount.h` line 365 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJBmjvh9vLwoStpubzY:-NJBmjvh9vLwoStpubzZ:b-3rlxb9) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/Refcount.h#L365)):*
> ```objc
>   }
>   /**
>    * The following functions correspond to whether or not an child
> ```

wrong description?
___
*[`cachelib/allocator/Refcount.h` line 374 at r5](https://reviewable.io/reviews/intel/cachelib/28#-NJBmdLhDD167CRFlh9j:-NJBmdLhDD167CRFlh9k:b4c0wz0) ([raw file](https://github.com/intel/cachelib/blob/3e0d65261673e81005f07d56861982be0b74ae86/cachelib/allocator/Refcount.h#L374)):*
> ```objc
>    * Unmarking moving does not depend on `isInMMContainer`
>    */
>   bool markChildMoving(bool failIfRefNotOne) {
> ```

how is this different from `markMoving`?

**Pull request closed without merging**
