### PR TITLE
[upstream] added per tier pool class rolling average latency

### PR DESCRIPTION
**Pull request by guptask**
This change is [Reviewable](https://reviewable.io/reviews/intel/cachelib/45)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/45)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @guptask)

___
*[`cachelib/allocator/Cache.h` line 89 at r1](https://reviewable.io/reviews/intel/cachelib/45#-NJlwekI4hOcMWj9pTRM:-NJlwekI4hOcMWj9pTRN:b-l3fhzk) ([raw file](https://github.com/intel/cachelib/blob/caa131871eb9d165627c42e85d57596c4f87a897/cachelib/allocator/Cache.h#L89)):*
> ```objc
> 
>   // TODO: come up with some reasonable number
>   static constexpr unsigned kMaxTiers = 2;
> ```

Can we not include any references to tiers in this PR? We could add support for tracking latency per class, per pool, right?
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 2231 at r1](https://reviewable.io/reviews/intel/cachelib/45#-NJlwsPEDWMfH7vdi47N:-NJlwsPEDWMfH7vdi47O:b-oc2iww) ([raw file](https://github.com/intel/cachelib/blob/caa131871eb9d165627c42e85d57596c4f87a897/cachelib/allocator/CacheAllocator-inl.h#L2231)):*
> ```objc
> 
> template <typename CacheTrait>
> double CacheAllocator<CacheTrait>::slabsApproxFreePercentage(TierId tid) const {
> ```

I think this should not part of the latency tracking patch.
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 2236 at r1](https://reviewable.io/reviews/intel/cachelib/45#-NJly5C--1A7-vgFpCkd:-NJly5C--1A7-vgFpCke:bpuoccl) ([raw file](https://github.com/intel/cachelib/blob/caa131871eb9d165627c42e85d57596c4f87a897/cachelib/allocator/CacheAllocator-inl.h#L2236)):*
> ```objc
> 
> template <typename CacheTrait>
> AllocationClassBaseStat CacheAllocator<CacheTrait>::getAllocationClassStats(
> ```

Same here, you should probably just store allocLatenencyNs. 

You can rebase onto https://github.com/intel/CacheLib/pull/42 perhaps and just use `getACStats` which I've added if you think it will be easier.

**Comment by guptask** [comment]
*[`cachelib/allocator/CacheAllocator-inl.h` line 2231 at r1](https://reviewable.io/reviews/intel/cachelib/45#-NJlwsPEDWMfH7vdi47N:-NKPlgv7DV3EupQqRiIQ:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/caa131871eb9d165627c42e85d57596c4f87a897/cachelib/allocator/CacheAllocator-inl.h#L2231)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think this should not part of the latency tracking patch.
</blockquote></details>

Done.

**Comment by guptask** [comment]
*[`cachelib/allocator/CacheAllocator-inl.h` line 2236 at r1](https://reviewable.io/reviews/intel/cachelib/45#-NJly5C--1A7-vgFpCkd:-NKPlj4X2_hy1kpImKkz:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/caa131871eb9d165627c42e85d57596c4f87a897/cachelib/allocator/CacheAllocator-inl.h#L2236)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Same here, you should probably just store allocLatenencyNs. 

You can rebase onto https://github.com/intel/CacheLib/pull/42 perhaps and just use `getACStats` which I've added if you think it will be easier.
</blockquote></details>

Done.

**Comment by guptask** [comment]
*[`cachelib/allocator/Cache.h` line 89 at r1](https://reviewable.io/reviews/intel/cachelib/45#-NJlwekI4hOcMWj9pTRM:-NKPle6237xc2nlTPxYd:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/caa131871eb9d165627c42e85d57596c4f87a897/cachelib/allocator/Cache.h#L89)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Can we not include any references to tiers in this PR? We could add support for tracking latency per class, per pool, right?
</blockquote></details>

Done.

**Comment by guptask** [comment]
I'm closing this PR and raising a new one that is rebased against Igor's AC Stats upstream PR (#42)

**Pull request closed without merging**
