### PR TITLE
Fix token creation and stuck SlabRelease

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/intel/cachelib/39)

### CODE REVIEW

**Review by byrnedj — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/39)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[`cachelib/allocator/CacheAllocator.h` line 1801 at r1](https://reviewable.io/reviews/intel/cachelib/39#-NJR2pc99KfTIPMJGBQ5:-NJR2pc99KfTIPMJGBQ6:b-l71i5e) ([raw file](https://github.com/intel/cachelib/blob/b6d63db513d315b1899cad2a0125941138dca832/cachelib/allocator/CacheAllocator.h#L1801)):*
> ```objc
> 
>   // wakes up waiters if there are any
>   void maybeWakeUpWaiters(Item& item, WriteHandle handle);
> ```

would you want to make the handle default to null? and maybe make a note about what the handle parameter should be - i.e.  new handle if item was moved or existing handle or null handle if evicted.



_Code snippet:_
```objc
maybeWakeUpWaiters(Item& item, WriteHandle handle = {})
```
___
*[`cachelib/allocator/CacheAllocator.h` line 1805 at r1](https://reviewable.io/reviews/intel/cachelib/39#-NJQtgEX0wV-AZp6Va0c:-NJQtgEX0wV-AZp6Va0d:b-v2mt4t) ([raw file](https://github.com/intel/cachelib/blob/b6d63db513d315b1899cad2a0125941138dca832/cachelib/allocator/CacheAllocator.h#L1805)):*
> ```objc
>   // unmarks item as moving and wakes up any waiters waiting on that item
>   typename RefcountWithFlags::Value unmarkMovingAndMaybeWakeUpWaiters(Item &item, WriteHandle handle = {});
> ```

I think the functionality - waking up waiters if there are any - works well. Also cherry picking this commit fixes some thread stuck waiting on a handle when I was testing some background evictor performance. So I can confirm function and performance wise the patch is good!

The nit change that I would recommend is if we renamed these functions so that we know the predicate based on the function name:
maybeWakeUpWaiters => wakeUpWaitersIfMultiTier 
unmarkMovingAndWakeUpWaitersIfMultiTier

Would we need to include these new wrappers in background movement methods traverseAndEvict? I think so if we plan to support single tier background eviction.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/39)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @byrnedj)

___
*[`cachelib/allocator/CacheAllocator.h` line 1801 at r1](https://reviewable.io/reviews/intel/cachelib/39#-NJR2pc99KfTIPMJGBQ5:-NJR8AFt45duHdPa7xtF:bz5jc0i) ([raw file](https://github.com/intel/cachelib/blob/b6d63db513d315b1899cad2a0125941138dca832/cachelib/allocator/CacheAllocator.h#L1801)):*
<details><summary><i>Previously, byrnedj (Daniel Byrne) wrote…</i></summary><blockquote>

would you want to make the handle default to null? and maybe make a note about what the handle parameter should be - i.e.  new handle if item was moved or existing handle or null handle if evicted.
</blockquote></details>

I've added the comment. I'm not sure about the default handle - I think it;s safer always to pass it (less chance of an error).
___
*[`cachelib/allocator/CacheAllocator.h` line 1805 at r1](https://reviewable.io/reviews/intel/cachelib/39#-NJQtgEX0wV-AZp6Va0c:-NJR9Zmq3aszvSxmjmIV:b-demn5y) ([raw file](https://github.com/intel/cachelib/blob/b6d63db513d315b1899cad2a0125941138dca832/cachelib/allocator/CacheAllocator.h#L1805)):*
<details><summary><i>Previously, byrnedj (Daniel Byrne) wrote…</i></summary><blockquote>

I think the functionality - waking up waiters if there are any - works well. Also cherry picking this commit fixes some thread stuck waiting on a handle when I was testing some background evictor performance. So I can confirm function and performance wise the patch is good!

The nit change that I would recommend is if we renamed these functions so that we know the predicate based on the function name:
maybeWakeUpWaiters => wakeUpWaitersIfMultiTier 
unmarkMovingAndWakeUpWaitersIfMultiTier

Would we need to include these new wrappers in background movement methods traverseAndEvict? I think so if we plan to support single tier background eviction.
</blockquote></details>

I actually prefer to keep the name more generic. We want to upstream the async item movement so it can be used even for single tier.

Yes, regarding bg eviction/promotion we need wake up the waiters as well. We really need some tests in CI for that.

**Review by byrnedj — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/39)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[`cachelib/allocator/CacheAllocator.h` line 1805 at r1](https://reviewable.io/reviews/intel/cachelib/39#-NJQtgEX0wV-AZp6Va0c:-NJRPHgOErhW8wfYXmpK:b-38b1bi) ([raw file](https://github.com/intel/cachelib/blob/b6d63db513d315b1899cad2a0125941138dca832/cachelib/allocator/CacheAllocator.h#L1805)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I actually prefer to keep the name more generic. We want to upstream the async item movement so it can be used even for single tier.

Yes, regarding bg eviction/promotion we need wake up the waiters as well. We really need some tests in CI for that.
</blockquote></details>

Okay, what about removing the word maybe (the subjunctive makes it hard to understand) and wakeUpWaiters would look like this (and we eliminate a function call in multi-tier case):



_Code snippet:_
```objc
    void wakeUpWaiters() {
      bool refcountOverflowed = false;
      if (getNumTiers() > 1) {
        for (auto& w : waiters) {
          // If refcount overflowed earlier, then we will return miss to
          // all subsequent waitors.
          if (refcountOverflowed) {
            w->set(WriteHandle{});
            continue;
          }

          try {
            w->set(it.clone());
          } catch (const exception::RefcountOverflow&) {
            // We'll return a miss to the user's pending read,
            // so we should enqueue a delete via NvmCache.
            // TODO: cache.remove(it);
            refcountOverflowed = true;
          }
        }
      }
    }
```

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/39)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @byrnedj)

___
*[`cachelib/allocator/CacheAllocator.h` line 1805 at r1](https://reviewable.io/reviews/intel/cachelib/39#-NJQtgEX0wV-AZp6Va0c:-NJR_HDyBEqWzcFNUhqo:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/b6d63db513d315b1899cad2a0125941138dca832/cachelib/allocator/CacheAllocator.h#L1805)):*
<details><summary><i>Previously, byrnedj (Daniel Byrne) wrote…</i></summary><blockquote>

Okay, what about removing the word maybe (the subjunctive makes it hard to understand) and wakeUpWaiters would look like this (and we eliminate a function call in multi-tier case):
</blockquote></details>

Done.

**Review by byrnedj — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/39)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor)

**Pull request merged**
