### PR TITLE
[upstream] use getCacheSize() in shm construction

### PR DESCRIPTION
**Pull request by byrnedj**
- Change the cache size calculation to use getCacheSize()
- Switch to isUsingPosixShm() method

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/cachelib/48)

### CODE REVIEW

**Review by vinser52 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/48)* status: all files reviewed, 1 unresolved discussion (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 138 at r1](https://reviewable.io/reviews/intel/cachelib/48#-NKxqIWbDgpFYhj7o8wi:-NKxqIWbDgpFYhj7o8wj:b-stlkgl) ([raw file](https://github.com/intel/cachelib/blob/08051fac544e305bdc364a482a4649b883e33960/cachelib/allocator/CacheAllocator-inl.h#L138)):*
> ```objc
>       shmManager_
>           ->attachShm(detail::kShmCacheName, config_.slabMemoryBaseAddr,
>                       createShmCacheOpts())
> ```

I think you should keep initial formating and just replace `config_.size` -> `config_.getCacheSize()`

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/48#-:-NKy4j8R66bksu--ksdl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @byrnedj)

**Review by byrnedj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/48)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @vinser52)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 138 at r1](https://reviewable.io/reviews/intel/cachelib/48#-NKxqIWbDgpFYhj7o8wi:-NKyxpLXDcrKzE0jaOFZ:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/08051fac544e305bdc364a482a4649b883e33960/cachelib/allocator/CacheAllocator-inl.h#L138)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I think you should keep initial formating and just replace `config_.size` -> `config_.getCacheSize()`
</blockquote></details>

Done.

**Review by vinser52 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/48)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @byrnedj)

**Review by vinser52 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/48#-:-NKz-EvRAK6xgSccnFrG:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @byrnedj)

**Review by igchor — COMMENTED** [review]
clang-format should be fixed 

> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/48#-:-NKzDOLH0hxii3mqlgWe:b-jesw2k)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @vinser52)

**Pull request closed without merging**
