### PR TITLE
[upstream] extend the memory tier config to work with NUMA bindings and add tests

### PR DESCRIPTION
**Pull request by byrnedj**
- Add memory tier configs to cache allocator based on NUMA bindings
- Add in MemoryTier tests
- Add getPoolSize() and inline the calculate tier size for tests
- Increase max number of tiers to 2 for tiers tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/cachelib/49)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/49)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @byrnedj and @vinser52)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 116 at r1](https://reviewable.io/reviews/intel/cachelib/49#-NKy7KFlCeynI24otxkB:-NKy7KFlCeynI24otxkC:buq510u) ([raw file](https://github.com/intel/cachelib/blob/f773d7ce228fe5bd9be0ec6470f187ae21949b29/cachelib/allocator/CacheAllocator-inl.h#L116)):*
> ```objc
>   XDCHECK_EQ(memoryTierConfigs.size(), 1ul);
>   opts.memBindNumaNodes = memoryTierConfigs[0].getMemBind();
>   if (memoryTierConfigs.size() > 1) {
> ```

There is already assert 2 lines above so we'll never reach this line if we have 2 tiers. Perhaps it might be better to throw this exception from Config (congiureMemoryTiers) for now?
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 2184 at r1](https://reviewable.io/reviews/intel/cachelib/49#-NKy5iqZ5EJ48ktHLG5s:-NKy5iqZ5EJ48ktHLG5t:bxnw08u) ([raw file](https://github.com/intel/cachelib/blob/f773d7ce228fe5bd9be0ec6470f187ae21949b29/cachelib/allocator/CacheAllocator-inl.h#L2184)):*
> ```objc
> 
> template <typename CacheTrait>
> size_t CacheAllocator<CacheTrait>::getPoolSize(PoolId poolId) const {
> ```

Do you actually need this function? I think you could call getPoolStats and get the size from there.
___
*[`cachelib/cachebench/util/CacheConfig.cpp` line 104 at r1](https://reviewable.io/reviews/intel/cachelib/49#-NKyAgkM1tFxEhI0yNI7:-NKyAgkM1tFxEhI0yNI8:b-pms6me) ([raw file](https://github.com/intel/cachelib/blob/f773d7ce228fe5bd9be0ec6470f187ae21949b29/cachelib/cachebench/util/CacheConfig.cpp#L104)):*
> ```cpp
>   JSONSetVal(configJson, customConfigJson);
>  
>   JSONSetVal(configJson, usePosixShm);
> ```

why it's duplicated?

**Review by vinser52 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/49)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[`cachelib/cachebench/util/CacheConfig.cpp` line 104 at r1](https://reviewable.io/reviews/intel/cachelib/49#-NKyAgkM1tFxEhI0yNI7:-NKz-hMw9kwwKhZwV71N:b-k7mqbv) ([raw file](https://github.com/intel/cachelib/blob/f773d7ce228fe5bd9be0ec6470f187ae21949b29/cachelib/cachebench/util/CacheConfig.cpp#L104)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why it's duplicated?
</blockquote></details>

Yeah, I think I already upstreamed these changes to Meta's main branch. Have you updated our main?

**Review by igchor — COMMENTED** [review]
clang-format should be fixed 

> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/49#-:-NKzDI2V5psDNqEfbeN-:b-jesw2k)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @byrnedj and @vinser52)

**Review by byrnedj — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/49#-:-NL0yo65DIsn_TTActmz:bb7f2mf)* status: 3 of 11 files reviewed, 3 unresolved discussions (waiting on @igchor and @vinser52)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 116 at r1](https://reviewable.io/reviews/intel/cachelib/49#-NKy7KFlCeynI24otxkB:-NL0ypUuCRmEtNlQocDn:b-yf5r70) ([raw file](https://github.com/intel/cachelib/blob/f773d7ce228fe5bd9be0ec6470f187ae21949b29/cachelib/allocator/CacheAllocator-inl.h#L116)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

There is already assert 2 lines above so we'll never reach this line if we have 2 tiers. Perhaps it might be better to throw this exception from Config (congiureMemoryTiers) for now?
</blockquote></details>

configureMemoryTiers will throw if greater than kMaxTiers, so I removed this line.
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 2184 at r1](https://reviewable.io/reviews/intel/cachelib/49#-NKy5iqZ5EJ48ktHLG5s:-NL0z-Qn57mdXW6WaEE0:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/f773d7ce228fe5bd9be0ec6470f187ae21949b29/cachelib/allocator/CacheAllocator-inl.h#L2184)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Do you actually need this function? I think you could call getPoolStats and get the size from there.
</blockquote></details>

Done.
___
*[`cachelib/cachebench/util/CacheConfig.cpp` line 104 at r1](https://reviewable.io/reviews/intel/cachelib/49#-NKyAgkM1tFxEhI0yNI7:-NL0z2X1Dy5N1-h8SYZj:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/f773d7ce228fe5bd9be0ec6470f187ae21949b29/cachelib/cachebench/util/CacheConfig.cpp#L104)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Yeah, I think I already upstreamed these changes to Meta's main branch. Have you updated our main?
</blockquote></details>

Done.

**Review by vinser52 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/49)* status: 3 of 11 files reviewed, 4 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[`cachelib/cachebench/util/CacheConfig.cpp` line 102 at r2](https://reviewable.io/reviews/intel/cachelib/49#-NL0zbaxEhXOwJWw_Je4:-NL0zbayBbvAi7gx7dcJ:b-3gz9gy) ([raw file](https://github.com/intel/cachelib/blob/08051fac544e305bdc364a482a4649b883e33960/cachelib/cachebench/util/CacheConfig.cpp#L102)):*
> ```cpp
>   JSONSetVal(configJson, nvmAdmissionRetentionTimeThreshold);
> 
>   JSONSetVal(configJson, customConfigJson);
> ```

Why this line is removed?

**Review by vinser52 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/49)* status: 4 of 11 files reviewed, 4 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 36 at r2](https://reviewable.io/reviews/intel/cachelib/49#-NL1-gQO7JewHkaGTTvU:-NL11wuQAFkow2lmZpZP:bdfo6bu) ([raw file](https://github.com/intel/cachelib/blob/461f9c55869676bebc2f3be9e4b99b7ab2ad09c0/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L36)):*
<details><summary><i>Previously, byrnedj (Daniel Byrne) wrote…</i></summary><blockquote>

No because I increase kMaxTiers to 2 in CacheAllocatorConfig.h
</blockquote></details>

In that case, I think we should throw an exception in the CacheAllocator constructor if (number of tiers > 1) because CacheAllocator is not enabled yet to support more then 1 tier.

**Review by byrnedj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/49)* status: 4 of 11 files reviewed, 4 unresolved discussions (waiting on @igchor and @vinser52)

___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 36 at r2](https://reviewable.io/reviews/intel/cachelib/49#-NL1-gQO7JewHkaGTTvU:-NL12inpCINStVdJNWQR:b-ilvw32) ([raw file](https://github.com/intel/cachelib/blob/461f9c55869676bebc2f3be9e4b99b7ab2ad09c0/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L36)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

In that case, I think we should throw an exception in the CacheAllocator constructor if (number of tiers > 1) because CacheAllocator is not enabled yet to support more then 1 tier. 
</blockquote></details>

We currently have assert in CacheAllocator constructor to check number of tiers == 1, if you think exception is better I can change.

**Review by vinser52 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/49)* status: 4 of 11 files reviewed, 4 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 36 at r2](https://reviewable.io/reviews/intel/cachelib/49#-NL1-gQO7JewHkaGTTvU:-NL131FM8nsudBlHkr3K:be4ke3a) ([raw file](https://github.com/intel/cachelib/blob/461f9c55869676bebc2f3be9e4b99b7ab2ad09c0/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L36)):*
<details><summary><i>Previously, byrnedj (Daniel Byrne) wrote…</i></summary><blockquote>

We currently have assert in CacheAllocator constructor to check number of tiers == 1, if you think exception is better I can change.
</blockquote></details>

Yeah, I think an exception is better because assert is usually used to check for an unexpected condition caused by a mistake in the code logic. In our case, config allows to set 2 tiers but CacheAllocator does not support it yet. In other words cache config is the external input and we cannot control it - it is better to throw an exception in that case.

**Review by byrnedj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/49)* status: 4 of 11 files reviewed, 4 unresolved discussions (waiting on @igchor and @vinser52)

___
*[`cachelib/allocator/tests/AllocatorMemoryTiersTest.h` line 36 at r2](https://reviewable.io/reviews/intel/cachelib/49#-NL1-gQO7JewHkaGTTvU:-NL1CcWTDFQuuTr_tqTU:b9nq5yq) ([raw file](https://github.com/intel/cachelib/blob/461f9c55869676bebc2f3be9e4b99b7ab2ad09c0/cachelib/allocator/tests/AllocatorMemoryTiersTest.h#L36)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Yeah, I think an exception is better because assert is usually used to check for an unexpected condition caused by a mistake in the code logic. In our case, config allows to set 2 tiers but CacheAllocator does not support it yet. In other words cache config is the external input and we cannot control it - it is better to throw an exception in that case.
</blockquote></details>

okay - done.

**Review by vinser52 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/49)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @igchor)

**Review by vinser52 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/49#-:-NL1Z42r0zWsrxDID2SX:bnfp4nl)* status: 4 of 11 files reviewed, 3 unresolved discussions (waiting on @igchor)

**Pull request closed without merging**
